# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "SFLSE_TEST"
user = "jmaragna"
password = "MLOps_Thesis_25!"
role = "ULTRASONIC_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
